export const FETCH_LOGIN_REQ = 'FETCH_LOGIN_REQ';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
export const UPDATE_AUTH_USER_DETAIL = 'UPDATE_AUTH_USER_DETAIL';
export const FAIL_UPDATE_AUTH_USER_DETAIL = 'FAIL_UPDATE_AUTH_USER_DETAIL';
export const SET_LOGOUT = 'SET_LOGOUT';